import { guardFormula } from "@/lib/finance/review/export";
import { describeColumn, NOT_EXPORTED, NOT_EXPORTED_COLUMNS, TABLES } from "./dictionary";
import type { ZipEntry } from "./zip";

export type CatalogColumn = { table_name: string; column_name: string; data_type: string; is_nullable: boolean; ordinal: number };
export type PackageRows = Record<string, Record<string, unknown>[]>;

export function csvCell(value: unknown): string {
  if (value === null || value === undefined) return "";
  const text = typeof value === "string" ? guardFormula(value) : typeof value === "object" ? JSON.stringify(value) : String(value);
  return /[",\r\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text;
}

export function tableCsv(columns: string[], rows: Record<string, unknown>[]): string {
  const lines = [columns.map(csvCell).join(",")];
  for (const row of rows) lines.push(columns.map((column) => csvCell(row[column])).join(","));
  return `﻿${lines.join("\r\n")}\r\n`;
}

export function groupCatalog(catalog: CatalogColumn[]): Map<string, CatalogColumn[]> {
  const tables = new Map<string, CatalogColumn[]>();
  for (const column of [...catalog].sort((a, b) => a.table_name.localeCompare(b.table_name) || a.ordinal - b.ordinal)) {
    const list = tables.get(column.table_name);
    if (list) list.push(column);
    else tables.set(column.table_name, [column]);
  }
  return tables;
}

export function undocumented(catalog: CatalogColumn[]): string[] {
  const missing: string[] = [];
  const tables = groupCatalog(catalog);
  for (const [table, columns] of tables) {
    if (!TABLES[table]) missing.push(table);
    for (const column of columns) if (!describeColumn(table, column.column_name)) missing.push(`${table}.${column.column_name}`);
  }
  return missing;
}

function readme(catalog: CatalogColumn[], counts: Record<string, number>, generatedAt: Date, generatedBy: string): string {
  const tables = groupCatalog(catalog);
  const out: string[] = [];
  out.push("LedgerLine data package");
  out.push("=======================");
  out.push("");
  out.push(`Generated: ${generatedAt.toISOString()}`);
  out.push(`Generated by: ${generatedBy}`);
  out.push("");
  out.push("All data in LedgerLine belongs to the New York City Council. This package holds a complete copy of it in open formats that need no LedgerLine software to read.");
  out.push("");
  out.push("Contents");
  out.push("--------");
  out.push("README.txt     This file.");
  out.push("manifest.csv   One row per table: the file name and the number of rows.");
  out.push("data/          One CSV file per table, with a header row of column names.");
  out.push("");
  out.push("How to read the files");
  out.push("---------------------");
  out.push("Files are UTF-8 text with comma separators and a header row. Quoted cells may contain line breaks.");
  out.push("Timestamps are ISO 8601 and carry their time zone offset. Dates are YYYY-MM-DD.");
  out.push("Cells that hold structured data (answers, form definitions, snapshots) contain JSON.");
  out.push("Text that begins with =, +, - or @ is prefixed with an apostrophe so spreadsheet programs do not run it as a formula. Remove the apostrophe to recover the original text.");
  out.push("Columns ending in _id, or named in the description as another table's id, point to the id column of that table.");
  out.push("");
  out.push("Files in storage");
  out.push("----------------");
  out.push("Uploaded supporting documents are held in file storage, not in this package. The attachment table lists each file with its path, name, size and type so each one can be retrieved from storage.");
  out.push("");
  out.push("Not included");
  out.push("------------");
  for (const item of NOT_EXPORTED) out.push(`${item.table}: ${item.reason}`);
  for (const item of NOT_EXPORTED_COLUMNS) out.push(`${item.table}.${item.column}: ${item.reason}`);
  out.push("");
  out.push("Tables");
  out.push("------");
  for (const [table, columns] of tables) {
    out.push("");
    out.push(`${table} (${counts[table] ?? 0} rows)`);
    out.push(`  ${TABLES[table]?.description ?? ""}`);
    for (const column of columns) {
      out.push(`  - ${column.column_name} [${column.data_type}${column.is_nullable ? ", may be empty" : ""}]: ${describeColumn(table, column.column_name) ?? ""}`);
    }
  }
  out.push("");
  return out.join("\n");
}

export function buildPackage(input: { catalog: CatalogColumn[]; rows: PackageRows; generatedAt: Date; generatedBy: string }): { files: ZipEntry[]; manifest: { table: string; file: string; rows: number }[] } {
  const tables = groupCatalog(input.catalog);
  const counts: Record<string, number> = {};
  const files: ZipEntry[] = [];
  const manifest: { table: string; file: string; rows: number }[] = [];
  for (const [table, columns] of tables) {
    const rows = input.rows[table] ?? [];
    counts[table] = rows.length;
    const file = `data/${table}.csv`;
    manifest.push({ table, file, rows: rows.length });
    files.push({ name: file, data: tableCsv(columns.map((c) => c.column_name), rows) });
  }
  const manifestCsv = tableCsv(["table", "file", "rows"], manifest);
  return {
    files: [{ name: "README.txt", data: readme(input.catalog, counts, input.generatedAt, input.generatedBy) }, { name: "manifest.csv", data: manifestCsv }, ...files],
    manifest,
  };
}
